project:
  type: book

book:
  title: "The Cnidarians"
  author: "Lewis A. Jones"
  date: today
  favicon: images/favicon_package_v0-3/favicon.ico
  search: true
  repo-url: https://github.com/LewisAJones/cnidaria
  repo-actions: [edit, issue]
  sharing: [twitter, facebook]
  page-footer: 
    left: "Copyright 2022, Lewis A. Jones" 
    right: 
      - icon: github
        href: https://github.com/LewisAJones
      - icon: twitter 
        href: https://twitter.com/LewisAlanJones
      - icon: cup
        href: https://www.buymeacoffee.com/LewisAJones
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - anthozoa.qmd
    - hexacorallia.qmd
    - octocorallia.qmd
    - medusozoa.qmd
    - staurozoa.qmd
    - cubozoa.qmd
    - scyphozoa.qmd
    - hydrozoa.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: pulse
      dark: vapor
  pdf:
    documentclass: scrreprt

editor: visual

