project:
  type: book

book:
  title: "The Cnidarians"
  author: "Lewis A. Jones"
  date: today
  favicon: images/favicon_package_v0-3/favicon.ico
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - anthozoa.qmd
    - hexacorallia.qmd
    - octocorallia.qmd
    - medusozoa.qmd
    - staurozoa.qmd
    - cubozoa.qmd
    - scyphozoa.qmd
    - hydrozoa.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

