project:
  type: book

book:
  title: "The Cnidaria"
  author: "Lewis A. Jones"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
favicon: images/favicon_package_v0-3/favicon.ico

editor: visual

